export const DefaultKeybinds = {
  'HidePlayer': 'AltRight',
  'ToggleControls': 'None',
  'PlayPause': 'Space',
  'Fullscreen': 'KeyF',
  'WindowedFullscreen': 'Shift+KeyW',
  'PictureInPicture': 'KeyP',
  'VolumeUp': 'ArrowUp',
  'VolumeDown': 'ArrowDown',
  'VolumeReset': 'None',
  'Mute': 'KeyM',
  'SeekForward': 'ArrowRight',
  'SeekBackward': 'ArrowLeft',
  'SeekForwardLarge': 'Period',
  'SeekBackwardLarge': 'Comma',
  'SeekForwardFrame': 'Shift+ArrowRight',
  'SeekBackwardFrame': 'Shift+ArrowLeft',
  'IncreasePlaybackRate': 'Shift+ArrowUp',
  'DecreasePlaybackRate': 'Shift+ArrowDown',
  'ResetPlaybackRate': 'None',
  'UndoSeek': 'KeyZ',
  'RedoSeek': 'Shift+KeyZ',
  'ResetFailed': 'Backquote',
  'AddDownloader': 'Equal',
  'RemoveDownloader': 'Minus',
  'PauseDownloaders': 'BracketLeft',
  'SaveVideo': 'KeyD',
  'Screenshot': 'KeyX',
  'SkipIntroOutro': 'KeyS',
  'NextChapter': 'Shift+KeyA',
  'GoToStart': 'Digit0',
  'SeekPercent10': 'Digit1',
  'SeekPercent20': 'Digit2',
  'SeekPercent30': 'Digit3',
  'SeekPercent40': 'Digit4',
  'SeekPercent50': 'Digit5',
  'SeekPercent60': 'Digit6',
  'SeekPercent70': 'Digit7',
  'SeekPercent80': 'Digit8',
  'SeekPercent90': 'Digit9',
  'NextVideo': 'KeyN',
  'PreviousVideo': 'Shift+KeyB',
  'ToggleSubtitles': 'KeyC',
  'ShiftSubtitlesEarlier': 'None',
  'ShiftSubtitlesLater': 'None',
  'FlipVideo': 'Shift+KeyE',
  'RotateVideo': 'Shift+KeyR',
  'ZoomInVideo': 'None',
  'ZoomOutVideo': 'None',
  'ZoomReset': 'None',
  'ToggleVisualFilters': 'Shift+KeyQ',
  // mpv-style speed presets (user's speed-presets.lua): key sets its speed,
  // pressing the SAME key again reverts to the previously active speed.
  'SpeedPreset1': 'KeyR',
  'SpeedPreset2': 'KeyG',
  'SpeedPreset2_5': 'KeyB',
  'SpeedPreset3': 'KeyQ',
  'SpeedPreset3_5': 'KeyW',
  'SpeedPreset4': 'KeyA',
  'SpeedPreset5': 'KeyY',
  'SpeedPreset8': 'KeyE',
  'SpeedPreset16': 'KeyH',
};

export const KeybindsWithModifiers = [
  'SaveVideo',
];
