// chrome/player/modules holds this project's own code next to vendored libraries, and the main
// config (eslint.config.js) skips the whole folder, style rules and all. That hid two calls to
// removed methods and an undefined function in shipped code. This checks the folder for the two
// mistakes that only show at run time, undefined and unused names, and leaves the vendored files
// out (the ones .gitignore lists are generated by tools/sync-vendor.mjs, the others are third
// party code kept as they came).
const globals = require('globals');

module.exports = [
  {
    ignores: [
      'chrome/player/modules/hls.mjs',
      'chrome/player/modules/hls.worker.js',
      'chrome/player/modules/dash.mjs',
      'chrome/player/modules/pako.mjs',
      'chrome/player/modules/fuse.mjs',
      'chrome/player/modules/sortable.mjs',
      'chrome/player/modules/sweetalert.mjs',
      'chrome/player/modules/mp4box.mjs',
      'chrome/player/modules/coloris.mjs',
      'chrome/player/modules/vad/ort.wasm.mjs',
      'chrome/player/modules/vad/ort-wasm-simd-threaded.mjs',
      'chrome/player/modules/reencoder/mp4-muxer.mjs',
      'chrome/player/modules/reencoder/webm.mjs',
      'chrome/player/modules/reencoder/libsamplerate.mjs',
      'chrome/player/modules/gif/',
      'chrome/player/modules/vtt.mjs',
    ],
  },
  {
    linterOptions: {reportUnusedDisableDirectives: 'off'},
    files: ['chrome/player/modules/**/*.{js,mjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.worker,
        ...globals.es2021,
        chrome: 'readonly',
        // AudioWorklet scope
        AudioWorkletProcessor: 'readonly',
        registerProcessor: 'readonly',
        sampleRate: 'readonly',
        currentFrame: 'readonly',
        currentTime: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': ['error', {args: 'none', caughtErrors: 'none'}],
    },
  },
];
